### PR TITLE
Task/translating tutorial

### PR DESCRIPTION
**Pull request by ChrisB9**

### CODE REVIEW

**Comment by miku86** [comment]
Hey @ChrisB9,

bisher ist ja bereits die Hälfte übersetzt, top :)
Benötigst du noch Hilfe?

**Comment by ChrisB9** [comment]
Danke für die Nachfrage, ich habe das Übersetzen ein bisschen schleifen lassen, bin jetzt aber wieder dran :+1:

**Comment by miku86** [comment]
@ChrisB9 

Hey Chris,

how are you doing?
I had a closer look at it, we are half way done. 
This page is really big, so I totally understand that this task is exhausting.

We should find an appropriate approach to tackle this page,
especially because it's an important one.

Do you need some help?
How can we help you to achieve this goal?

Please give some feedback, if you can manage to translate it,
let's say until the end of November. That's four weeks from now.

Thanks & Greetings
Michael

**Comment by ChrisB9** [comment]
Hi @miku86 

yes, the page is big, but the work on it continuous, i just haven't pushed my stuff in a while, so its already i little more then half. (65% to 70% or so) 

I guess the only way you can help is looking over my old translations and spellchecking them once in a while, that way i can incorporate errors or style changes along the way.

End of November sounds like an appropriate time frame to manage this last bit of translation,

cheers and thanks for asking :)
Chris

**Comment by liza-kl** [comment]
Hi @ChrisB9,
how is your progress with the translation going?

And can I help you with something else, rather than just look at the old translations? 

Thanks & best regards,
Lisa

**Comment by ChrisB9** [comment]
> Hi @ChrisB9,
> how is your progress with the translation going?
> 
> And can I help you with something else, rather than just look at the old translations?
> 
> Thanks & best regards,
> Lisa

Hey @liza-kl ,

if you want, you can continue it however you like :)

Cheers

**Comment by justbyBen** [comment]
There are quite a lot grammar and typing mistakes in this pr...
May I fix the bugs? @ChrisB9

**Comment by ChrisB9** [comment]
> There are quite a lot grammar and typing mistakes in this pr...
> May I fix the bugs? @ChrisB9

Absolutely, go ahead, you can pin me on the PR when you feel like you are done and I'll have a look then

**Comment by mnlfischer** [comment]
Hi @ChrisB9,

do you need help?

**Comment by TheFireCircle** [comment]
Hi @ChrisB9,
is any help needed?
And how could I help you?
Maybe we can integrate this PR soon because I think a tutorial is a very essential part of the website.

Thanks!

**Comment by ChrisB9** [comment]
@mnlfischer @TheFireCircle just continue it. I currently have zero time to work on it, so feel free to finish it up and ping me once you feel its done

**Comment by TheFireCircle** [comment]
@ChrisB9 okay, progress can be tracked on this [branch](https://github.com/TheFireCircle/de.reactjs.org/tree/ale/translating-tutorial).

**Comment by TheFireCircle** [comment]
> @mnlfischer @TheFireCircle just continue it. I currently have zero time to work on it, so feel free to finish it up and ping me once you feel its done

Hello @ChrisB9, I just opened a [PR](https://github.com/reactjs/de.reactjs.org/pull/290) with the changes of the mentioned branch. Feel free to check it out :)

**Pull request closed without merging**
